var figure = {
    "frames": [], 
    "layout": {
        "autosize": true, 
        "xaxis": {
            "range": [
                -0.5, 
                539.5
            ], 
            "type": "category", 
            "autorange": true
        }, 
        "yaxis": {
            "range": [
                -16.111111111111114, 
                306.1111111111111
            ], 
            "type": "category", 
            "autorange": true
        }
    }, 
    "data": [
        {
            "orientation": "v", 
            "ysrc": "Koka.Alyafei:8:1088c3", 
            "xsrc": "Koka.Alyafei:8:1391c5", 
            "mode": "markers", 
            "y": [
                "Acquiring Institution", 
                "Royal Savings Bank", 
                "Conway Bank", 
                "United Fidelity Bank, fsb", 
                "First-Citizens Bank & Trust Company", 
                "Whitney Bank", 
                "Cache Valley Bank", 
                "State Bank of Texas", 
                "First-Citizens Bank & Trust Company", 
                "Today's Bank", 
                "United Bank", 
                "First-Citizens Bank & Trust Company", 
                "The Bank of Fayette County", 
                "First-Citizens Bank & Trust Company", 
                "Twin City Bank", 
                "Fidelity Bank", 
                "United Fidelity Bank, fsb", 
                "Republic Bank of Chicago", 
                "Banco Popular de Puerto Rico", 
                "First-Citizens Bank & Trust Company", 
                "United Fidelity Bank, fsb", 
                "First NBC Bank", 
                "BankVista", 
                "Bank of Southern California, N.A.", 
                "State Bank of Texas", 
                "Howard Bank", 
                "Providence Bank, LLC", 
                "Community & Southern Bank", 
                "Alva State Bank & Trust Company", 
                "Landmark Bank, National Association", 
                "Great Southern Bank", 
                "Bay Bank, FSB", 
                "United Fidelity Bank, fsb", 
                "Republic Bank of Chicago", 
                "Palmetto State Bank", 
                "First Choice Bank", 
                "WashingtonFirst Bank", 
                "Sunwest Bank", 
                "BancFirst", 
                "Republic Bank of Chicago", 
                "Spirit of Texas Bank, SSB", 
                "First Federal Bank of Florida", 
                "PlainsCapital Bank", 
                "No Acquirer", 
                "First Fidelity Bank, National Association", 
                "CB&S Bank, Inc.", 
                "Nicolet National Bank", 
                "C1 Bank", 
                "First Tennessee Bank, National Association", 
                "Plaza Bank", 
                "North Shore Bank, FSB", 
                "Western State Bank", 
                "Synovus Bank", 
                "Capital Bank, N.A.", 
                "Hamilton State Bank", 
                "CertusBank, National Association", 
                "First Federal Bank of Florida", 
                "FirstAtlantic Bank", 
                "Your Community Bank", 
                "First Scottsdale Bank, National Association", 
                "HeritageBank of the South", 
                "Liberty Bank and Trust Company", 
                "First Minnesota Bank", 
                "Sunwest Bank", 
                "Bank of Sullivan", 
                "CertusBank, National Association", 
                "Heartland Bank and Trust Company", 
                "Centennial Bank", 
                "No Acquirer", 
                "Simmons First National Bank", 
                "Stearns Bank N.A.", 
                "SmartBank", 
                "Old Plank Trail Community Bank, National Association", 
                "Simmons First National Bank", 
                "Republic Bank & Trust Company", 
                "First Midwest Bank", 
                "Stearns Bank N.A.", 
                "Hinsdale Bank & Trust Company", 
                "Metcalf Bank", 
                "Community & Southern Bank", 
                "Community & Southern Bank", 
                "First National Bank of the Gulf Coast", 
                "Regional Missouri Bank", 
                "Ameris Bank", 
                "Clayton Bank and Trust", 
                "Fidelity Bank", 
                "Harbor Community Bank", 
                "First Community Bank", 
                "First State Bank", 
                "Bank of North Carolina", 
                "F & M Bank", 
                "Southern States Bank", 
                "Banesco USA", 
                "Pacific Premier Bank", 
                "First Federal Bank", 
                "Great Southern Bank", 
                "Sonabank", 
                "No Acquirer", 
                "Alma Bank", 
                "The Huntington National Bank", 
                "International Bank of Chicago", 
                "Stearns Bank, N.A.", 
                "No Acquirer", 
                "Metro City Bank", 
                "No Acquirer", 
                "Ameris Bank", 
                "First Merchants Bank, National Association", 
                "Barrington Bank & Trust Company, National Association", 
                "U.S. Bank, N.A.", 
                "First Resource Bank", 
                "Republic Bank & Trust Company", 
                "CenterState Bank of Florida, N.A.", 
                "Capital Bank, N.A.", 
                "Hamilton State Bank", 
                "CenterState Bank of Florida, N.A.", 
                "Washington Federal", 
                "Summit Bank", 
                "First NBC Bank", 
                "Grinnell State Bank", 
                "Century Bank of Georgia", 
                "Cache Valley Bank", 
                "Premier Bank", 
                "International Bank of Chicago", 
                "Bank Midwest, N.A.", 
                "State Bank and Trust Company", 
                "Fidelity Bank", 
                "1st United Bank", 
                "Blackhawk Bank & Trust", 
                "Northfield Bank", 
                "Bank of North Carolina", 
                "State Bank and Trust Company", 
                "Great Southern Bank", 
                "Central Bank", 
                "American First National Bank", 
                "Tri Counties Bank", 
                "Southern Bank and Trust Company", 
                "CharterBank", 
                "Georgia Commerce Bank", 
                "Georgia Commerce Bank", 
                "Inland Bank & Trust", 
                "Heritage Bank of the South", 
                "Sabadell United Bank, N.A.", 
                "Capital Bank, N.A.", 
                "Enterprise Bank & Trust", 
                "Columbia State Bank", 
                "Heartland Bank and Trust Company", 
                "Old National Bank", 
                "SCBT National Association", 
                "Xenith Bank", 
                "Bank Midwest, N.A.", 
                "American Momentum Bank", 
                "American Momentum Bank", 
                "The Foothills Bank", 
                "Premier American Bank, N.A.", 
                "Ameris Bank", 
                "Ameris Bank", 
                "Points West Community Bank", 
                "First-Citizens Bank & Trust Company", 
                "Northbrook Bank & Trust Company", 
                "First American Bank and Trust Company", 
                "Stonegate Bank", 
                "Hamilton State Bank", 
                "First Citizens Bank and Trust Company, Inc.", 
                "Columbia State Bank", 
                "Columbia State Bank", 
                "CertusBank, National Association", 
                "CertusBank, National Association", 
                "Florida Community Bank, a division of Premier American Bank, N.A.", 
                "Talmer Bank & Trust", 
                "Bank of the Ozarks", 
                "Bank of the Ozarks", 
                "Florida Community Bank, a division of Premier American Bank, N.A.", 
                "Florida Community Bank, a division of Premier American Bank, N.A.", 
                "Trustmark National Bank", 
                "Central Bank", 
                "Superior Bank, National Association", 
                "AloStar Bank of Commerce", 
                "Citizens South Bank", 
                "Hamilton State Bank", 
                "City National Bank", 
                "Heartland Bank and Trust Company", 
                "Advantage National Bank Group", 
                "Seaway Bank and Trust Company", 
                "The Pauls Valley National Bank", 
                "First State Bank", 
                "First California Bank", 
                "Bank of Marin", 
                "Heritage Bank of the South", 
                "SCBT National Association", 
                "Pacific Premier Bank", 
                "Royal Bank", 
                "First Michigan Bank", 
                "Premier American Bank, N.A.", 
                "Northbrook Bank & Trust Company", 
                "BankSouth", 
                "Renasant Bank", 
                "U.S. Bank, N.A.", 
                "No Acquirer", 
                "McFarland State Bank", 
                "Bank 7", 
                "First-Citizens Bank & Trust Company", 
                "First Bank", 
                "CertusBank, National Association", 
                "No Acquirer", 
                "Bank of the Ozarks", 
                "Enterprise Bank & Trust", 
                "First Southern Bank", 
                "Farmers & Merchants Savings Bank", 
                "Southern Bank", 
                "State Bank and Trust Company", 
                "Peoples Bank of East Tennessee", 
                "Bank of the Ozarks", 
                "1st United Bank", 
                "Polonia Bank", 
                "Level One Bank", 
                "First Michigan Bank", 
                "VIST Bank", 
                "Centennial Bank", 
                "Stearns Bank, N.A.", 
                "Ameris Bank", 
                "Ameris Bank", 
                "Grandpoint Bank", 
                "Heritage Bank", 
                "First California Bank", 
                "Manufacturers and Traders Trust Company (M&T Bank)", 
                "No Acquirer", 
                "Hillcrest Bank, N.A.", 
                "Seaway Bank and Trust Company", 
                "United Bank", 
                "Morris Bank", 
                "Bay Cities Bank", 
                "Ameris Bank", 
                "Providence Bank", 
                "Midland States Bank", 
                "Simmons First National Bank", 
                "GBC International Bank", 
                "Centennial Bank", 
                "Whidbey Island Bank", 
                "First Southern Bank", 
                "North Shore Bank, FSB", 
                "Foundation Bank", 
                "Community & Southern Bank", 
                "Community & Southern Bank", 
                "Community & Southern Bank", 
                "Customers Bank", 
                "Bank of the Ozarks", 
                "Westamerica Bank", 
                "Pacific Western Bank", 
                "Rabobank, N.A.", 
                "Rabobank, N.A.", 
                "Urban Partnership Bank", 
                "River Community Bank, N.A.", 
                "CenterState Bank of Florida, N.A.", 
                "CenterState Bank of Florida, N.A.", 
                "First Midwest Bank", 
                "Northbrook Bank & Trust Company", 
                "Home Federal Bank", 
                "Heritage Bank", 
                "Centennial Bank", 
                "Centennial Bank", 
                "State Bank and Trust Company", 
                "South Valley Bank & Trust", 
                "Plaza Bank", 
                "Roundbank", 
                "The Bennington State Bank", 
                "First Citizens Bank and Trust Company, Inc.", 
                "Renasant Bank", 
                "IBERIABANK", 
                "Commercial Bank", 
                "CenterState Bank of Florida, N.A.", 
                "NAFH National Bank", 
                "NAFH National Bank", 
                "NAFH National Bank", 
                "Bank of the Ozarks", 
                "RCB Bank", 
                "New Century Bank", 
                "No Acquirer", 
                "Bay Bank, FSB", 
                "First American Bank", 
                "The Savannah Bank, N.A.", 
                "Premier American Bank, N.A.", 
                "Umpqua Bank", 
                "East West Bank", 
                "Great Western Bank", 
                "No Acquirer", 
                "The Jefferson Bank", 
                "City National Bank", 
                "Tri Counties Bank", 
                "EverBank", 
                "EverBank", 
                "EverBank", 
                "Coulee Bank", 
                "FirstMerit Bank, N.A.", 
                "Simmons First National Bank", 
                "Bank of Ann Arbor", 
                "Ameris Bank", 
                "City National Bank", 
                "Commerce Bank of Arizona", 
                "PrinsBank", 
                "First Federal Bank of Florida", 
                "Union Bank, N.A.", 
                "Community First Bank", 
                "BankLiberty", 
                "First Michigan Bank", 
                "Banco Popular de Puerto Rico", 
                "Scotiabank de Puerto Rico", 
                "Oriental Bank and Trust", 
                "Wheaton Bank & Trust", 
                "First Midwest Bank", 
                "Northbrook Bank & Trust Company", 
                "MB Financial Bank, N.A.", 
                "Republic Bank of Chicago", 
                "MB Financial Bank, N.A.", 
                "Harris N.A.", 
                "Whidbey Island Bank", 
                "Union Bank, N.A.", 
                "Center Bank", 
                "People's United Bank", 
                "TD Bank, N.A.", 
                "TD Bank, N.A.", 
                "TD Bank, N.A.", 
                "No Acquirer", 
                "Bank of North Carolina", 
                "New York Community Bank", 
                "Bank of the Ozarks", 
                "Centennial Bank", 
                "CharterBank", 
                "Northern State Bank", 
                "First Citizens Bank", 
                "Citizens South Bank", 
                "Community & Southern Bank", 
                "No Acquirer", 
                "Bank of Upson", 
                "The National Bank and Trust Company", 
                "Home Bank", 
                "Centennial Bank", 
                "Valley National Bank", 
                "Valley National Bank", 
                "No Acquirer", 
                "No Acquirer", 
                "Heartland Bank and Trust Company", 
                "First-Citizens Bank & Trust Company", 
                "Umpqua Bank", 
                "Heritage Bank of Nevada", 
                "OneWest Bank, FSB", 
                "FirstMerit Bank, N.A.", 
                "Community National Bank", 
                "Mutual of Omaha Bank", 
                "Community Development Bank, FSB", 
                "Columbia State Bank", 
                "First-Citizens Bank & Trust Company", 
                "SCBT National Association", 
                "United Valley Bank", 
                "Premier American Bank, N.A.", 
                "Community & Southern Bank", 
                "Columbia State Bank", 
                "Umpqua Bank", 
                "Charter Bank", 
                "Sunflower Bank, N.A.", 
                "Premier American Bank, N.A.", 
                "No Acquirer", 
                "First State Bank of St. Joseph", 
                "First American Bank", 
                "Washington Federal Savings and Loan Association", 
                "OneWest Bank, FSB", 
                "City National Bank", 
                "The Independent BankersBank (TIB)", 
                "Beal Bank", 
                "No Acquirer", 
                "Hancock Bank", 
                "No Acquirer", 
                "Arvest Bank", 
                "Enterprise Bank & Trust", 
                "1st United Bank", 
                "Sonabank", 
                "MB Financial Bank, N.A.", 
                "New York Community Bank", 
                "Heritage Bank of the South", 
                "State Bank and Trust Company", 
                "State Bank and Trust Company", 
                "Central Bank", 
                "Sunwest Bank", 
                "IBERIABANK", 
                "IBERIABANK", 
                "East West Bank", 
                "Central Bank of Kansas City", 
                "Alerus Financial, N.A.", 
                "Liberty Bank and Trust Company", 
                "Ameris Bank", 
                "U.S. Bank N.A.", 
                "U.S. Bank N.A.", 
                "U.S. Bank N.A.", 
                "U.S. Bank N.A.", 
                "U.S. Bank N.A.", 
                "U.S. Bank N.A.", 
                "U.S. Bank N.A.", 
                "U.S. Bank N.A.", 
                "U.S. Bank N.A.", 
                "First Midwest Bank", 
                "Central Bank", 
                "Tri City National Bank", 
                "First Federal Bank of Florida", 
                "Stonegate Bank", 
                "Ameris Bank", 
                "Stonegate Bank", 
                "Citizens Business Bank", 
                "Legacy Bank", 
                "Central Bank", 
                "The Huntington National Bank", 
                "First Citizens Bank and Trust Company, Inc.", 
                "First Financial Bank, N.A.", 
                "First Financial Bank, N.A.", 
                "First-Citizens Bank & Trust Company", 
                "CorTrust Bank N.A.", 
                "MB Financial Bank, N.A.", 
                "Sunwest Bank", 
                "No Acquirer", 
                "Great Southern Bank", 
                "MB Financial Bank, N.A.", 
                "Great American Bank", 
                "Pacific Western Bank", 
                "Central Bank", 
                "Manufacturers and Traders Trust Company (M&T Bank)", 
                "BBVA Compass", 
                "IBERIABANK", 
                "United Bank", 
                "Stearns Bank, N.A.", 
                "No Acquirer", 
                "MidFirst Bank", 
                "MidFirst Bank", 
                "Branch Banking & Trust Company, (BB&T)", 
                "PNC Bank, N.A.", 
                "Home Federal Bank", 
                "Stearns Bank, N.A.", 
                "Stearns Bank, N.A.", 
                "United Central Bank", 
                "Crown Bank", 
                "First Financial Bank, N.A.", 
                "Stonegate Bank", 
                "Herring Bank", 
                "State Bank and Trust Company", 
                "State Bank and Trust Company", 
                "State Bank and Trust Company", 
                "State Bank and Trust Company", 
                "State Bank and Trust Company", 
                "State Bank and Trust Company", 
                "Evans Bank, N.A.", 
                "First-Citizens Bank & Trust Company", 
                "California Bank & Trust", 
                "Alerus Financial, N.A.", 
                "First American Bank and Trust Company", 
                "Central Bank & Trust", 
                "The PrivateBank and Trust Company", 
                "State Bank of Texas", 
                "First Financial Bank, N.A.", 
                "Galena State Bank and Trust Company", 
                "The Harvard State Bank", 
                "The First National Bank of Beardstown", 
                "State Bank of Lincoln", 
                "Wilshire State Bank", 
                "Sunwest Bank", 
                "Stearns Bank, N.A.", 
                "CharterBank", 
                "No Acquirer", 
                "Bank of Kansas", 
                "First Bank", 
                "United Community Bank", 
                "Republic Bank of Chicago", 
                "Morton Community Bank", 
                "Midland States Bank", 
                "BankUnited", 
                "Kitsap Bank", 
                "Cache Valley Bank", 
                "North Jersey Community Bank", 
                "No Acquirer", 
                "U.S. Bank, N.A.", 
                "No Acquirer", 
                "Level One Bank", 
                "Bank of North Georgia", 
                "Nevada State Bank", 
                "Metcalf Bank", 
                "No Acquirer", 
                "First Federal Savings and Loan Association", 
                "No Acquirer", 
                "Great Southern Bank", 
                "Herring Bank", 
                "No Acquirer", 
                "Northeast Georgia Bank", 
                "Bank of Nevada", 
                "MB Financial Bank, N.A.", 
                "Citizens Bank", 
                "Washington Trust Bank of Spokane", 
                "The Carlinville National Bank", 
                "TIB Bank", 
                "Heritage Bank", 
                "Westamerica Bank", 
                "California Bank & Trust", 
                "Regions Bank", 
                "CenterState Bank of Florida, N.A.", 
                "Bank of Essex", 
                "No Acquirer", 
                "First California Bank", 
                "Umpqua Bank", 
                "Republic Bank of Chicago", 
                "The Pecos County State Bank", 
                "Branch Banking & Trust Company, (BB&T)", 
                "United Bank", 
                "U.S. Bank, N.A.", 
                "U.S. Bank, N.A.", 
                "Bank of Essex", 
                "Pacific Western Bank", 
                "Prosperity Bank", 
                "Fifth Third Bank", 
                "Stearns Bank, N.A.", 
                "National Bank", 
                "Monroe Bank & Trust", 
                "JP Morgan Chase Bank", 
                "The Citizens Savings Bank, Pioneer Community Bank, Inc.", 
                "Nevada State Bank", 
                "Regions Bank", 
                "Citizens Bank & Trust", 
                "SunTrust Bank", 
                "Mutual of Omaha Bank", 
                "Mutual of Omaha Bank", 
                "OneWest Bank, FSB", 
                "First International Bank and Trust", 
                "Pulaski Bank and Trust Company", 
                "Security Bank", 
                "Liberty Bank and Trust Company", 
                "The Citizens Banking Company", 
                "ING DIRECT", 
                "Allegheny Valley Bank of Pittsburgh", 
                "Far West Bank", 
                "Union State Bank", 
                "Hancock Bank of Florida", 
                "No Acquirer", 
                "Earthstar Bank", 
                "The Park Bank", 
                "Beal Bank", 
                "Sabine State Bank & Trust", 
                "No Acquirer", 
                "No Acquirer", 
                "Chicago Community Bank", 
                "Hudson United Bank", 
                "No Acquirer", 
                "Bank Leumi USA", 
                "No Acquirer", 
                "The State Bank & Trust Company", 
                "The Security State Bank of Pecos", 
                "Israel Discount Bank of New York", 
                "Delta Trust & Bank", 
                "Superior Federal, FSB", 
                "North Valley Bank", 
                "Southern New Hampshire Bank & Trust", 
                "Banterra Bank of Marion", 
                "Bank of the Orient"
            ], 
            "x": [
                "Bank Name", 
                "Washington Federal Bank for Savings", 
                "The Farmers and Merchants State Bank of Argonia", 
                "Fayette County Bank", 
                "Guaranty Bank, (d/b/a BestBank in Georgia & Michigan)", 
                "First NBC Bank", 
                "Proficio Bank", 
                "Seaway Bank and Trust Company", 
                "Harvest Community Bank", 
                "Allied Bank", 
                "The Woodbury Banking Company", 
                "First CornerStone Bank", 
                "Trust Company Bank", 
                "North Milwaukee State Bank", 
                "Hometown National Bank", 
                "The Bank of Georgia", 
                "Premier Bank", 
                "Edgebrook Bank", 
                "Doral Bank", 
                "Capitol City Bank & Trust Company", 
                "Highland Community Bank", 
                "First National Bank of Crestview", 
                "Northern Star Bank", 
                "Frontier Bank, FSB D/B/A El Paseo Bank", 
                "The National Republic Bank of Chicago", 
                "NBRS Financial", 
                "GreenChoice Bank, fsb", 
                "Eastside Commercial Bank", 
                "The Freedom State Bank", 
                "Valley Bank", 
                "Valley Bank", 
                "Slavie Federal Savings Bank", 
                "Columbia Savings Bank", 
                "AztecAmerica Bank ", 
                "Allendale County Bank", 
                "Vantage Point Bank", 
                "Millennium Bank, National Association", 
                "Syringa Bank", 
                "The Bank of Union", 
                "DuPage National Bank", 
                "Texas Community Bank, National Association", 
                "Bank of Jackson County", 
                "First National Bank also operating as The National Bank of El Paso ", 
                "The Community's Bank", 
                "Sunrise Bank of Arizona", 
                "Community South Bank", 
                "Bank of Wausau", 
                "First Community Bank of Southwest Florida (also operating as Community Bank of Cape Coral)", 
                "Mountain National Bank", 
                "1st Commerce Bank", 
                "Banks of Wisconsin d/b/a Bank of Kenosha", 
                "Central Arizona Bank", 
                "Sunrise Bank", 
                "Pisgah Community Bank", 
                "Douglas County Bank", 
                "Parkway Bank", 
                "Chipola Community Bank", 
                "Heritage Bank of North Florida", 
                "First Federal Bank", 
                "Gold Canyon Bank", 
                "Frontier Bank", 
                "Covenant Bank", 
                "1st Regents Bank", 
                "Westside Community Bank", 
                "Community Bank of the Ozarks", 
                "Hometown Community Bank", 
                "Citizens First National Bank", 
                "Heritage Bank of Florida", 
                "NOVA Bank", 
                "Excel Bank", 
                "First East Side Savings Bank", 
                "GulfSouth Private Bank", 
                "First United Bank", 
                "Truman Bank", 
                "First Commercial Bank", 
                "Waukegan Savings Bank", 
                "Jasper Banking Company", 
                "Second Federal Savings and Loan Association of Chicago", 
                "Heartland Bank", 
                "First Cherokee State Bank", 
                "Georgia Trust Bank", 
                "The Royal Palm Bank of Florida", 
                "Glasgow Savings Bank", 
                "Montgomery Bank & Trust", 
                "The Farmers Bank of Lynchburg", 
                "Security Exchange Bank", 
                "Putnam State Bank", 
                "Waccamaw Bank", 
                "Farmers' and Traders' State Bank", 
                "Carolina Federal Savings Bank", 
                "First Capital Bank", 
                "Alabama Trust Bank, National Association", 
                "Security Bank, National Association", 
                "Palm Desert National Bank", 
                "Plantation Federal Bank", 
                "Inter Savings Bank, fsb D/B/A InterBank, fsb", 
                "HarVest Bank of Maryland", 
                "Bank of the Eastern Shore", 
                "Fort Lee Federal Savings Bank, FSB", 
                "Fidelity Bank", 
                "Premier Bank", 
                "Covenant Bank & Trust", 
                "New City Bank", 
                "Global Commerce Bank", 
                "Home Savings of America", 
                "Central Bank of Georgia", 
                "SCB Bank", 
                "Charter National Bank and Trust", 
                "BankEast", 
                "Patriot Bank Minnesota", 
                "Tennessee Commerce Bank", 
                "First Guaranty Bank and Trust Company of Jacksonville", 
                "American Eagle Savings Bank", 
                "The First State Bank", 
                "Central Florida State Bank", 
                "Western National Bank", 
                "Premier Community Bank of the Emerald Coast", 
                "Central Progressive Bank", 
                "Polk County Bank", 
                "Community Bank of Rockmart", 
                "SunFirst Bank", 
                "Mid City Bank, Inc.", 
                "All American Bank", 
                "Community Banks of Colorado", 
                "Community Capital Bank", 
                "Decatur First Bank", 
                "Old Harbor Bank", 
                "Country Bank", 
                "First State Bank", 
                "Blue Ridge Savings Bank, Inc.", 
                "Piedmont Community Bank", 
                "Sun Security Bank", 
                "The RiverBank", 
                "First International Bank", 
                "Citizens Bank of Northern California", 
                "Bank of the Commonwealth", 
                "The First National Bank of Florida", 
                "CreekSide Bank", 
                "Patriot Bank of Georgia", 
                "First Choice Bank", 
                "First Southern National Bank", 
                "Lydian Private Bank", 
                "Public Savings Bank", 
                "The First National Bank of Olathe", 
                "Bank of Whitman", 
                "Bank of Shorewood", 
                "Integra Bank National Association", 
                "BankMeridian, N.A.", 
                "Virginia Business Bank", 
                "Bank of Choice", 
                "LandMark Bank of Florida", 
                "Southshore Community Bank", 
                "Summit Bank", 
                "First Peoples Bank", 
                "High Trust Bank", 
                "One Georgia Bank", 
                "Signature Bank", 
                "Colorado Capital Bank", 
                "First Chicago Bank & Trust", 
                "Mountain Heritage Bank", 
                "First Commercial Bank of Tampa Bay", 
                "McIntosh State Bank", 
                "Atlantic Bank and Trust", 
                "First Heritage Bank", 
                "Summit Bank", 
                "First Georgia Banking Company", 
                "Atlantic Southern Bank", 
                "Coastal Bank", 
                "Community Central Bank", 
                "The Park Avenue Bank", 
                "First Choice Community Bank", 
                "Cortez Community Bank", 
                "First National Bank of Central Florida", 
                "Heritage Banking Group", 
                "Rosemount National Bank", 
                "Superior Bank", 
                "Nexity Bank", 
                "New Horizons Bank", 
                "Bartow County Bank", 
                "Nevada Commerce Bank", 
                "Western Springs National Bank and Trust", 
                "The Bank of Commerce", 
                "Legacy Bank", 
                "First National Bank of Davis", 
                "Valley Community Bank", 
                "San Luis Trust Bank, FSB", 
                "Charter Oak Bank", 
                "Citizens Bank of Effingham", 
                "Habersham Bank", 
                "Canyon National Bank", 
                "Badger State Bank", 
                "Peoples State Bank", 
                "Sunshine State Community Bank", 
                "Community First Bank Chicago", 
                "North Georgia Bank", 
                "American Trust Bank", 
                "First Community Bank", 
                "FirsTier Bank", 
                "Evergreen State Bank", 
                "The First State Bank", 
                "United Western Bank", 
                "The Bank of Asheville", 
                "CommunitySouth Bank & Trust", 
                "Enterprise Banking Company", 
                "Oglethorpe Bank", 
                "Legacy Bank", 
                "First Commercial Bank of Florida", 
                "Community National Bank", 
                "First Southern Bank", 
                "United Americas Bank, N.A.", 
                "Appalachian Community Bank, FSB", 
                "Chestatee State Bank", 
                "The Bank of Miami,N.A.", 
                "Earthstar Bank", 
                "Paramount Bank", 
                "First Banking Center", 
                "Allegiance Bank of North America", 
                "Gulf State Community Bank", 
                "Copper Star Bank", 
                "Darby Bank & Trust Co.", 
                "Tifton Banking Company", 
                "First Vietnamese American Bank", 
                "Pierce Commercial Bank", 
                "Western Commercial Bank", 
                "K Bank", 
                "First Arizona Savings, A FSB", 
                "Hillcrest Bank", 
                "First Suburban National Bank", 
                "The First National Bank of Barnesville", 
                "The Gordon Bank", 
                "Progress Bank of Florida", 
                "First Bank of Jacksonville", 
                "Premier Bank", 
                "WestBridge Bank and Trust Company", 
                "Security Savings Bank, F.S.B.", 
                "Shoreline Bank", 
                "Wakulla Bank", 
                "North County Bank", 
                "Haven Trust Bank Florida", 
                "Maritime Savings Bank", 
                "Bramble Savings Bank", 
                "The Peoples Bank", 
                "First Commerce Community Bank", 
                "Bank of Ellijay", 
                "ISN Bank", 
                "Horizon Bank", 
                "Sonoma Valley Bank", 
                "Los Padres Bank", 
                "Butte Community Bank", 
                "Pacific State Bank", 
                "ShoreBank", 
                "Imperial Savings and Loan Association", 
                "Independent National Bank", 
                "Community National Bank at Bartow", 
                "Palos Bank and Trust Company", 
                "Ravenswood Bank", 
                "LibertyBank", 
                "The Cowlitz Bank", 
                "Coastal Community Bank", 
                "Bayside Savings Bank", 
                "Northwest Bank & Trust", 
                "Home Valley Bank", 
                "SouthwestUSA Bank", 
                "Community Security Bank", 
                "Thunder Bank", 
                "Williamsburg First National Bank", 
                "Crescent Bank and Trust Company", 
                "Sterling Bank", 
                "Mainstreet Savings Bank, FSB", 
                "Olde Cypress Community Bank", 
                "Turnberry Bank", 
                "Metro Bank of Dade County", 
                "First National Bank of the South", 
                "Woodlands Bank", 
                "Home National Bank", 
                "USA Bank", 
                "Ideal Federal Savings Bank", 
                "Bay National Bank", 
                "High Desert State Bank", 
                "First National Bank", 
                "Peninsula Bank", 
                "Nevada Security Bank", 
                "Washington First International Bank", 
                "TierOne Bank", 
                "Arcola Homestead Savings Bank", 
                "First National Bank", 
                "Sun West Bank", 
                "Granite Community Bank, NA", 
                "Bank of Florida - Tampa", 
                "Bank of Florida - Southwest", 
                "Bank of Florida - Southeast", 
                "Pinehurst Bank", 
                "Midwest Bank and Trust Company", 
                "Southwest Community Bank", 
                "New Liberty Bank", 
                "Satilla Community Bank", 
                "1st Pacific Bank of California", 
                "Towne Bank of Arizona", 
                "Access Bank", 
                "The Bank of Bonifay", 
                "Frontier Bank", 
                "BC National Banks", 
                "Champion Bank", 
                "CF Bancorp", 
                "Westernbank Puerto Rico", 
                "R-G Premier Bank of Puerto Rico", 
                "Eurobank", 
                "Wheatland Bank", 
                "Peotone Bank and Trust Company", 
                "Lincoln Park Savings Bank", 
                "New Century Bank", 
                "Citizens Bank and Trust Company of Chicago", 
                "Broadway Bank", 
                "Amcore Bank, National Association", 
                "City Bank", 
                "Tamalpais Bank", 
                "Innovative Bank", 
                "Butler Bank", 
                "Riverside National Bank of Florida", 
                "AmericanFirst Bank", 
                "First Federal Bank of North Florida", 
                "Lakeside Community Bank", 
                "Beach First National Bank", 
                "Desert Hills Bank", 
                "Unity National Bank", 
                "Key West Bank", 
                "McIntosh Commercial Bank", 
                "State Bank of Aurora", 
                "First Lowndes Bank", 
                "Bank of Hiawassee", 
                "Appalachian Community Bank", 
                "Advanta Bank Corp.", 
                "Century Security Bank", 
                "American National Bank", 
                "Statewide Bank", 
                "Old Southern Bank", 
                "The Park Avenue Bank", 
                "LibertyPointe Bank", 
                "Centennial Bank", 
                "Waterfield Bank", 
                "Bank of Illinois", 
                "Sun American Bank", 
                "Rainier Pacific Bank", 
                "Carson River Community Bank", 
                "La Jolla Bank, FSB", 
                "George Washington Savings Bank", 
                "The La Coste National Bank", 
                "Marco Community Bank", 
                "1st American State Bank of Minnesota", 
                "American Marine Bank", 
                "First Regional Bank", 
                "Community Bank and Trust", 
                "Marshall Bank, N.A.", 
                "Florida Community Bank", 
                "First National Bank of Georgia", 
                "Columbia River Bank", 
                "Evergreen Bank", 
                "Charter Bank", 
                "Bank of Leeton", 
                "Premier American Bank", 
                "Barnes Banking Company", 
                "St. Stephen State Bank", 
                "Town Community Bank & Trust", 
                "Horizon Bank", 
                "First Federal Bank of California, F.S.B.", 
                "Imperial Capital Bank", 
                "Independent Bankers' Bank", 
                "New South Federal Savings Bank", 
                "Citizens State Bank", 
                "Peoples First Community Bank", 
                "RockBridge Commercial Bank", 
                "SolutionsBank", 
                "Valley Capital Bank, N.A.", 
                "Republic Federal Bank, N.A.", 
                "Greater Atlantic Bank", 
                "Benchmark Bank", 
                "AmTrust Bank", 
                "The Tattnall Bank", 
                "First Security National Bank", 
                "The Buckhead Community Bank", 
                "Commerce Bank of Southwest Florida", 
                "Pacific Coast National Bank", 
                "Orion Bank", 
                "Century Bank, F.S.B.", 
                "United Commercial Bank", 
                "Gateway Bank of St. Louis", 
                "Prosperan Bank", 
                "Home Federal Savings Bank", 
                "United Security Bank", 
                "North Houston Bank", 
                "Madisonville State Bank", 
                "Citizens National Bank", 
                "Park National Bank", 
                "Pacific National Bank", 
                "California National Bank", 
                "San Diego National Bank", 
                "Community Bank of Lemont", 
                "Bank USA, N.A.", 
                "First DuPage Bank", 
                "Riverview Community Bank", 
                "Bank of Elmwood", 
                "Flagship National Bank", 
                "Hillcrest Bank Florida", 
                "American United Bank", 
                "Partners Bank", 
                "San Joaquin Bank", 
                "Southern Colorado National Bank", 
                "Jennings State Bank", 
                "Warren Bank", 
                "Georgian Bank", 
                "Irwin Union Bank, F.S.B.", 
                "Irwin Union Bank and Trust Company", 
                "Venture Bank", 
                "Brickwell Community Bank", 
                "Corus Bank, N.A.", 
                "First State Bank", 
                "Platinum Community Bank", 
                "Vantus Bank", 
                "InBank", 
                "First Bank of Kansas City", 
                "Affinity Bank", 
                "Mainstreet Bank", 
                "Bradford Bank", 
                "Guaranty Bank", 
                "CapitalSouth Bank", 
                "First Coweta Bank", 
                "ebank", 
                "Community Bank of Nevada", 
                "Community Bank of Arizona", 
                "Union Bank, National Association", 
                "Colonial Bank", 
                "Dwelling House Savings and Loan Association", 
                "Community First Bank", 
                "Community National Bank of Sarasota County", 
                "First State Bank", 
                "Mutual Bank", 
                "First BankAmericano", 
                "Peoples Community Bank", 
                "Integrity Bank", 
                "First State Bank of Altus", 
                "Security Bank of Jones County", 
                "Security Bank of Houston County", 
                "Security Bank of Bibb County", 
                "Security Bank of North Metro", 
                "Security Bank of North Fulton", 
                "Security Bank of Gwinnett County", 
                "Waterford Village Bank", 
                "Temecula Valley Bank", 
                "Vineyard Bank", 
                "BankFirst", 
                "First Piedmont Bank", 
                "Bank of Wyoming", 
                "Founders Bank", 
                "Millennium State Bank of Texas", 
                "First National Bank of Danville", 
                "The Elizabeth State Bank", 
                "Rock River Bank", 
                "First State Bank of Winchester", 
                "John Warner Bank", 
                "Mirae Bank", 
                "MetroPacific Bank", 
                "Horizon Bank", 
                "Neighborhood Community Bank", 
                "Community Bank of West Georgia", 
                "First National Bank of Anthony", 
                "Cooperative Bank", 
                "Southern Community Bank", 
                "Bank of Lincolnwood", 
                "Citizens National Bank", 
                "Strategic Capital Bank", 
                "BankUnited, FSB", 
                "Westsound Bank", 
                "America West Bank", 
                "Citizens Community Bank", 
                "Silverton Bank, NA", 
                "First Bank of Idaho", 
                "First Bank of Beverly Hills", 
                "Michigan Heritage Bank", 
                "American Southern Bank", 
                "Great Basin Bank of Nevada", 
                "American Sterling Bank", 
                "New Frontier Bank", 
                "Cape Fear Bank", 
                "Omni National Bank", 
                "TeamBank, NA", 
                "Colorado National Bank", 
                "FirstCity Bank", 
                "Freedom Bank of Georgia", 
                "Security Savings Bank", 
                "Heritage Community Bank", 
                "Silver Falls Bank", 
                "Pinnacle Bank of Oregon", 
                "Corn Belt Bank & Trust Co.", 
                "Riverside Bank of the Gulf Coast", 
                "Sherman County Bank", 
                "County Bank", 
                "Alliance Bank", 
                "FirstBank Financial Services", 
                "Ocala National Bank", 
                "Suburban FSB", 
                "MagnetBank", 
                "1st Centennial Bank", 
                "Bank of Clark County", 
                "National Bank of Commerce", 
                "Sanderson State Bank", 
                "Haven Trust Bank", 
                "First Georgia Community Bank", 
                "PFF Bank & Trust", 
                "Downey Savings & Loan", 
                "Community Bank", 
                "Security Pacific Bank", 
                "Franklin Bank, SSB", 
                "Freedom Bank", 
                "Alpha Bank & Trust", 
                "Meridian Bank", 
                "Main Street Bank", 
                "Washington Mutual Bank, (Including its subsidiary Washington Mutual Bank FSB)", 
                "Ameribank", 
                "Silver State Bank", 
                "Integrity Bank", 
                "Columbian Bank & Trust", 
                "First Priority Bank", 
                "First Heritage Bank, NA", 
                "First National Bank of Nevada", 
                "IndyMac Bank", 
                "First Integrity Bank, NA", 
                "ANB Financial, NA", 
                "Hume Bank", 
                "Douglass National Bank", 
                "Miami Valley Bank", 
                "NetBank", 
                "Metropolitan Savings Bank", 
                "Bank of Ephraim", 
                "Reliance Bank", 
                "Guaranty National Bank of Tallahassee", 
                "Dollar Savings Bank", 
                "Pulaski Savings Bank", 
                "First National Bank of Blanchardville", 
                "Southern Pacific Bank", 
                "Farmers Bank of Cheneyville", 
                "Bank of Alamo", 
                "AmTrade International Bank", 
                "Universal Federal Savings Bank", 
                "Connecticut Bank of Commerce", 
                "New Century Bank", 
                "Net 1st National Bank", 
                "NextBank, NA", 
                "Oakwood Deposit Bank Co.", 
                "Bank of Sierra Blanca", 
                "Hamilton Bank, NA", 
                "Sinclair National Bank", 
                "Superior Bank, FSB", 
                "Malta National Bank", 
                "First Alliance Bank & Trust Co.", 
                "National State Bank of Metropolis", 
                "Bank of Honolulu"
            ], 
            "type": "bar"
        }
    ]
}