var figure = {
    "frames": [], 
    "layout": {
        "xaxis": {
            "rangeselector": {
                "buttons": [
                    {
                        "count": 1, 
                        "step": "month", 
                        "stepmode": "backward", 
                        "label": "1m"
                    }, 
                    {
                        "count": 6, 
                        "step": "month", 
                        "stepmode": "backward", 
                        "label": "6m"
                    }, 
                    {
                        "count": 1, 
                        "step": "year", 
                        "stepmode": "todate", 
                        "label": "YTD"
                    }, 
                    {
                        "count": 1, 
                        "step": "year", 
                        "stepmode": "backward", 
                        "label": "1y"
                    }, 
                    {
                        "step": "all"
                    }
                ]
            }, 
            "type": "date", 
            "rangeslider": {
                "visible": true
            }
        }, 
        "title": "Time series for Bank failure"
    }, 
    "data": [
        {
            "uid": "76e887fd-f9f2-4ffb-a1a3-e2e25cfa4f94", 
            "ysrc": "Koka.Alyafei:7:674810", 
            "xsrc": "Koka.Alyafei:7:edcd0c", 
            "y": [
                "Washington Federal Bank for Savings", 
                "The Farmers and Merchants State Bank of Argonia", 
                "Fayette County Bank", 
                "Guaranty Bank, (d/b/a BestBank in Georgia & Michigan)", 
                "First NBC Bank", 
                "Proficio Bank", 
                "Seaway Bank and Trust Company", 
                "Harvest Community Bank", 
                "Allied Bank", 
                "The Woodbury Banking Company", 
                "First CornerStone Bank", 
                "Trust Company Bank", 
                "North Milwaukee State Bank", 
                "Hometown National Bank", 
                "The Bank of Georgia", 
                "Premier Bank", 
                "Edgebrook Bank", 
                "Doral Bank", 
                "Capitol City Bank & Trust Company", 
                "Highland Community Bank", 
                "First National Bank of Crestview", 
                "Northern Star Bank", 
                "Frontier Bank, FSB D/B/A El Paseo Bank", 
                "The National Republic Bank of Chicago", 
                "NBRS Financial", 
                "GreenChoice Bank, fsb", 
                "Eastside Commercial Bank", 
                "The Freedom State Bank", 
                "Valley Bank", 
                "Valley Bank", 
                "Slavie Federal Savings Bank", 
                "Columbia Savings Bank", 
                "AztecAmerica BankÂ ", 
                "Allendale County Bank", 
                "Vantage Point Bank", 
                "Millennium Bank, National Association", 
                "Syringa Bank", 
                "The Bank of Union", 
                "DuPage National Bank", 
                "Texas Community Bank, National Association", 
                "Bank of Jackson County", 
                "First National Bank also operating as The National Bank of El PasoÂ ", 
                "The Community's Bank", 
                "Sunrise Bank of Arizona", 
                "Community South Bank", 
                "Bank of Wausau", 
                "First Community Bank of Southwest Florida (also operating as Community Bank of Cape Coral)", 
                "Mountain National Bank", 
                "1st Commerce Bank", 
                "Banks of Wisconsin d/b/a Bank of Kenosha", 
                "Central Arizona Bank", 
                "Sunrise Bank", 
                "Pisgah Community Bank", 
                "Douglas County Bank", 
                "Parkway Bank", 
                "Chipola Community Bank", 
                "Heritage Bank of North Florida", 
                "First Federal Bank", 
                "Gold Canyon Bank", 
                "Frontier Bank", 
                "Covenant Bank", 
                "1st Regents Bank", 
                "Westside Community Bank", 
                "Community Bank of the Ozarks", 
                "Hometown Community Bank", 
                "Citizens First National Bank", 
                "Heritage Bank of Florida", 
                "NOVA Bank", 
                "Excel Bank", 
                "First East Side Savings Bank", 
                "GulfSouth Private Bank", 
                "First United Bank", 
                "Truman Bank", 
                "First Commercial Bank", 
                "Waukegan Savings Bank", 
                "Jasper Banking Company", 
                "Second Federal Savings and Loan Association of Chicago", 
                "Heartland Bank", 
                "First Cherokee State Bank", 
                "Georgia Trust Bank", 
                "The Royal Palm Bank of Florida", 
                "Glasgow Savings Bank", 
                "Montgomery Bank & Trust", 
                "The Farmers Bank of Lynchburg", 
                "Security Exchange Bank", 
                "Putnam State Bank", 
                "Waccamaw Bank", 
                "Farmers' and Traders' State Bank", 
                "Carolina Federal Savings Bank", 
                "First Capital Bank", 
                "Alabama Trust Bank, National Association", 
                "Security Bank, National Association", 
                "Palm Desert National Bank", 
                "Plantation Federal Bank", 
                "Inter Savings Bank, fsb D/B/A InterBank, fsb", 
                "HarVest Bank of Maryland", 
                "Bank of the Eastern Shore", 
                "Fort Lee Federal Savings Bank, FSB", 
                "Fidelity Bank", 
                "Premier Bank", 
                "Covenant Bank & Trust", 
                "New City Bank", 
                "Global Commerce Bank", 
                "Home Savings of America", 
                "Central Bank of Georgia", 
                "SCB Bank", 
                "Charter National Bank and Trust", 
                "BankEast", 
                "Patriot Bank Minnesota", 
                "Tennessee Commerce Bank", 
                "First Guaranty Bank and Trust Company of Jacksonville", 
                "American Eagle Savings Bank", 
                "The First State Bank", 
                "Central Florida State Bank", 
                "Western National Bank", 
                "Premier Community Bank of the Emerald Coast", 
                "Central Progressive Bank", 
                "Polk County Bank", 
                "Community Bank of Rockmart", 
                "SunFirst Bank", 
                "Mid City Bank, Inc.", 
                "All American Bank", 
                "Community Banks of Colorado", 
                "Community Capital Bank", 
                "Decatur First Bank", 
                "Old Harbor Bank", 
                "Country Bank", 
                "First State Bank", 
                "Blue Ridge Savings Bank, Inc.", 
                "Piedmont Community Bank", 
                "Sun Security Bank", 
                "The RiverBank", 
                "First International Bank", 
                "Citizens Bank of Northern California", 
                "Bank of the Commonwealth", 
                "The First National Bank of Florida", 
                "CreekSide Bank", 
                "Patriot Bank of Georgia", 
                "First Choice Bank", 
                "First Southern National Bank", 
                "Lydian Private Bank", 
                "Public Savings Bank", 
                "The First National Bank of Olathe", 
                "Bank of Whitman", 
                "Bank of Shorewood", 
                "Integra Bank National Association", 
                "BankMeridian, N.A.", 
                "Virginia Business Bank", 
                "Bank of Choice", 
                "LandMark Bank of Florida", 
                "Southshore Community Bank", 
                "Summit Bank", 
                "First Peoples Bank", 
                "High Trust Bank", 
                "One Georgia Bank", 
                "Signature Bank", 
                "Colorado Capital Bank", 
                "First Chicago Bank & Trust", 
                "Mountain Heritage Bank", 
                "First Commercial Bank of Tampa Bay", 
                "McIntosh State Bank", 
                "Atlantic Bank and Trust", 
                "First Heritage Bank", 
                "Summit Bank", 
                "First Georgia Banking Company", 
                "Atlantic Southern Bank", 
                "Coastal Bank", 
                "Community Central Bank", 
                "The Park Avenue Bank", 
                "First Choice Community Bank", 
                "Cortez Community Bank", 
                "First National Bank of Central Florida", 
                "Heritage Banking Group", 
                "Rosemount National Bank", 
                "Superior Bank", 
                "Nexity Bank", 
                "New Horizons Bank", 
                "Bartow County Bank", 
                "Nevada Commerce Bank", 
                "Western Springs National Bank and Trust", 
                "The Bank of Commerce", 
                "Legacy Bank", 
                "First National Bank of Davis", 
                "Valley Community Bank", 
                "San Luis Trust Bank, FSB", 
                "Charter Oak Bank", 
                "Citizens Bank of Effingham", 
                "Habersham Bank", 
                "Canyon National Bank", 
                "Badger State Bank", 
                "Peoples State Bank", 
                "Sunshine State Community Bank", 
                "Community First Bank Chicago", 
                "North Georgia Bank", 
                "American Trust Bank", 
                "First Community Bank", 
                "FirsTier Bank", 
                "Evergreen State Bank", 
                "The First State Bank", 
                "United Western Bank", 
                "The Bank of Asheville", 
                "CommunitySouth Bank & Trust", 
                "Enterprise Banking Company", 
                "Oglethorpe Bank", 
                "Legacy Bank", 
                "First Commercial Bank of Florida", 
                "Community National Bank", 
                "First Southern Bank", 
                "United Americas Bank, N.A.", 
                "Appalachian Community Bank, FSB", 
                "Chestatee State Bank", 
                "The Bank of Miami,N.A.", 
                "Earthstar Bank", 
                "Paramount Bank", 
                "First Banking Center", 
                "Allegiance Bank of North America", 
                "Gulf State Community Bank", 
                "Copper Star Bank", 
                "Darby Bank & Trust Co.", 
                "Tifton Banking Company", 
                "First Vietnamese American Bank", 
                "Pierce Commercial Bank", 
                "Western Commercial Bank", 
                "K Bank", 
                "First Arizona Savings, A FSB", 
                "Hillcrest Bank", 
                "First Suburban National Bank", 
                "The First National Bank of Barnesville", 
                "The Gordon Bank", 
                "Progress Bank of Florida", 
                "First Bank of Jacksonville", 
                "Premier Bank", 
                "WestBridge Bank and Trust Company", 
                "Security Savings Bank, F.S.B.", 
                "Shoreline Bank", 
                "Wakulla Bank", 
                "North County Bank", 
                "Haven Trust Bank Florida", 
                "Maritime Savings Bank", 
                "Bramble Savings Bank", 
                "The Peoples Bank", 
                "First Commerce Community Bank", 
                "Bank of Ellijay", 
                "ISN Bank", 
                "Horizon Bank", 
                "Sonoma Valley Bank", 
                "Los Padres Bank", 
                "Butte Community Bank", 
                "Pacific State Bank", 
                "ShoreBank", 
                "Imperial Savings and Loan Association", 
                "Independent National Bank", 
                "Community National Bank at Bartow", 
                "Palos Bank and Trust Company", 
                "Ravenswood Bank", 
                "LibertyBank", 
                "The Cowlitz Bank", 
                "Coastal Community Bank", 
                "Bayside Savings Bank", 
                "Northwest Bank & Trust", 
                "Home Valley Bank", 
                "SouthwestUSA Bank", 
                "Community Security Bank", 
                "Thunder Bank", 
                "Williamsburg First National Bank", 
                "Crescent Bank and Trust Company", 
                "Sterling Bank", 
                "Mainstreet Savings Bank, FSB", 
                "Olde Cypress Community Bank", 
                "Turnberry Bank", 
                "Metro Bank of Dade County", 
                "First National Bank of the South", 
                "Woodlands Bank", 
                "Home National Bank", 
                "USA Bank", 
                "Ideal Federal Savings Bank", 
                "Bay National Bank", 
                "High Desert State Bank", 
                "First National Bank", 
                "Peninsula Bank", 
                "Nevada Security Bank", 
                "Washington First International Bank", 
                "TierOne Bank", 
                "Arcola Homestead Savings Bank", 
                "First National Bank", 
                "Sun West Bank", 
                "Granite Community Bank, NA", 
                "Bank of Florida - Tampa", 
                "Bank of Florida - Southwest", 
                "Bank of Florida - Southeast", 
                "Pinehurst Bank", 
                "Midwest Bank and Trust Company", 
                "Southwest Community Bank", 
                "New Liberty Bank", 
                "Satilla Community Bank", 
                "1st Pacific Bank of California", 
                "Towne Bank of Arizona", 
                "Access Bank", 
                "The Bank of Bonifay", 
                "Frontier Bank", 
                "BC National Banks", 
                "Champion Bank", 
                "CF Bancorp", 
                "Westernbank Puerto Rico", 
                "R-G Premier Bank of Puerto Rico", 
                "Eurobank", 
                "Wheatland Bank", 
                "Peotone Bank and Trust Company", 
                "Lincoln Park Savings Bank", 
                "New Century Bank", 
                "Citizens Bank and Trust Company of Chicago", 
                "Broadway Bank", 
                "Amcore Bank, National Association", 
                "City Bank", 
                "Tamalpais Bank", 
                "Innovative Bank", 
                "Butler Bank", 
                "Riverside National Bank of Florida", 
                "AmericanFirst Bank", 
                "First Federal Bank of North Florida", 
                "Lakeside Community Bank", 
                "Beach First National Bank", 
                "Desert Hills Bank", 
                "Unity National Bank", 
                "Key West Bank", 
                "McIntosh Commercial Bank", 
                "State Bank of Aurora", 
                "First Lowndes Bank", 
                "Bank of Hiawassee", 
                "Appalachian Community Bank", 
                "Advanta Bank Corp.", 
                "Century Security Bank", 
                "American National Bank", 
                "Statewide Bank", 
                "Old Southern Bank", 
                "The Park Avenue Bank", 
                "LibertyPointe Bank", 
                "Centennial Bank", 
                "Waterfield Bank", 
                "Bank of Illinois", 
                "Sun American Bank", 
                "Rainier Pacific Bank", 
                "Carson River Community Bank", 
                "La Jolla Bank, FSB", 
                "George Washington Savings Bank", 
                "The La Coste National Bank", 
                "Marco Community Bank", 
                "1st American State Bank of Minnesota", 
                "American Marine Bank", 
                "First Regional Bank", 
                "Community Bank and Trust", 
                "Marshall Bank, N.A.", 
                "Florida Community Bank", 
                "First National Bank of Georgia", 
                "Columbia River Bank", 
                "Evergreen Bank", 
                "Charter Bank", 
                "Bank of Leeton", 
                "Premier American Bank", 
                "Barnes Banking Company", 
                "St. Stephen State Bank", 
                "Town Community Bank & Trust", 
                "Horizon Bank", 
                "First Federal Bank of California, F.S.B.", 
                "Imperial Capital Bank", 
                "Independent Bankers' Bank", 
                "New South Federal Savings Bank", 
                "Citizens State Bank", 
                "Peoples First Community Bank", 
                "RockBridge Commercial Bank", 
                "SolutionsBank", 
                "Valley Capital Bank, N.A.", 
                "Republic Federal Bank, N.A.", 
                "Greater Atlantic Bank", 
                "Benchmark Bank", 
                "AmTrust Bank", 
                "The Tattnall Bank", 
                "First Security National Bank", 
                "The Buckhead Community Bank", 
                "Commerce Bank of Southwest Florida", 
                "Pacific Coast National Bank", 
                "Orion Bank", 
                "Century Bank, F.S.B.", 
                "United Commercial Bank", 
                "Gateway Bank of St. Louis", 
                "Prosperan Bank", 
                "Home Federal Savings Bank", 
                "United Security Bank", 
                "North Houston Bank", 
                "Madisonville State Bank", 
                "Citizens National Bank", 
                "Park National Bank", 
                "Pacific National Bank", 
                "California National Bank", 
                "San Diego National Bank", 
                "Community Bank of Lemont", 
                "Bank USA, N.A.", 
                "First DuPage Bank", 
                "Riverview Community Bank", 
                "Bank of Elmwood", 
                "Flagship National Bank", 
                "Hillcrest Bank Florida", 
                "American United Bank", 
                "Partners Bank", 
                "San Joaquin Bank", 
                "Southern Colorado National Bank", 
                "Jennings State Bank", 
                "Warren Bank", 
                "Georgian Bank", 
                "Irwin Union Bank, F.S.B.", 
                "Irwin Union Bank and Trust Company", 
                "Venture Bank", 
                "Brickwell Community Bank", 
                "Corus Bank, N.A.", 
                "First State Bank", 
                "Platinum Community Bank", 
                "Vantus Bank", 
                "InBank", 
                "First Bank of Kansas City", 
                "Affinity Bank", 
                "Mainstreet Bank", 
                "Bradford Bank", 
                "Guaranty Bank", 
                "CapitalSouth Bank", 
                "First Coweta Bank", 
                "ebank", 
                "Community Bank of Nevada", 
                "Community Bank of Arizona", 
                "Union Bank, National Association", 
                "Colonial Bank", 
                "Dwelling House Savings and Loan Association", 
                "Community First Bank", 
                "Community National Bank of Sarasota County", 
                "First State Bank", 
                "Mutual Bank", 
                "First BankAmericano", 
                "Peoples Community Bank", 
                "Integrity Bank", 
                "First State Bank of Altus", 
                "Security Bank of Jones County", 
                "Security Bank of Houston County", 
                "Security Bank of Bibb County", 
                "Security Bank of North Metro", 
                "Security Bank of North Fulton", 
                "Security Bank of Gwinnett County", 
                "Waterford Village Bank", 
                "Temecula Valley Bank", 
                "Vineyard Bank", 
                "BankFirst", 
                "First Piedmont Bank", 
                "Bank of Wyoming", 
                "Founders Bank", 
                "Millennium State Bank of Texas", 
                "First National Bank of Danville", 
                "The Elizabeth State Bank", 
                "Rock River Bank", 
                "First State Bank of Winchester", 
                "John Warner Bank", 
                "Mirae Bank", 
                "MetroPacific Bank", 
                "Horizon Bank", 
                "Neighborhood Community Bank", 
                "Community Bank of West Georgia", 
                "First National Bank of Anthony", 
                "Cooperative Bank", 
                "Southern Community Bank", 
                "Bank of Lincolnwood", 
                "Citizens National Bank", 
                "Strategic Capital Bank", 
                "BankUnited, FSB", 
                "Westsound Bank", 
                "America West Bank", 
                "Citizens Community Bank", 
                "Silverton Bank, NA", 
                "First Bank of Idaho", 
                "First Bank of Beverly Hills", 
                "Michigan Heritage Bank", 
                "American Southern Bank", 
                "Great Basin Bank of Nevada", 
                "American Sterling Bank", 
                "New Frontier Bank", 
                "Cape Fear Bank", 
                "Omni National Bank", 
                "TeamBank, NA", 
                "Colorado National Bank", 
                "FirstCity Bank", 
                "Freedom Bank of Georgia", 
                "Security Savings Bank", 
                "Heritage Community Bank", 
                "Silver Falls Bank", 
                "Pinnacle Bank of Oregon", 
                "Corn Belt Bank & Trust Co.", 
                "Riverside Bank of the Gulf Coast", 
                "Sherman County Bank", 
                "County Bank", 
                "Alliance Bank", 
                "FirstBank Financial Services", 
                "Ocala National Bank", 
                "Suburban FSB", 
                "MagnetBank", 
                "1st Centennial Bank", 
                "Bank of Clark County", 
                "National Bank of Commerce", 
                "Sanderson State Bank", 
                "Haven Trust Bank", 
                "First Georgia Community Bank", 
                "PFF Bank & Trust", 
                "Downey Savings & Loan", 
                "Community Bank", 
                "Security Pacific Bank", 
                "Franklin Bank, SSB", 
                "Freedom Bank", 
                "Alpha Bank & Trust", 
                "Meridian Bank", 
                "Main Street Bank", 
                "Washington Mutual Bank, (Including its subsidiary Washington Mutual Bank FSB)", 
                "Ameribank", 
                "Silver State Bank", 
                "Integrity Bank", 
                "Columbian Bank & Trust", 
                "First Priority Bank", 
                "First Heritage Bank, NA", 
                "First National Bank of Nevada", 
                "IndyMac Bank", 
                "First Integrity Bank, NA", 
                "ANB Financial, NA", 
                "Hume Bank", 
                "Douglass National Bank", 
                "Miami Valley Bank", 
                "NetBank", 
                "Metropolitan Savings Bank", 
                "Bank of Ephraim", 
                "Reliance Bank", 
                "Guaranty National Bank of Tallahassee", 
                "Dollar Savings Bank", 
                "Pulaski Savings Bank", 
                "First National Bank of Blanchardville", 
                "Southern Pacific Bank", 
                "Farmers Bank of Cheneyville", 
                "Bank of Alamo", 
                "AmTrade International Bank", 
                "Universal Federal Savings Bank", 
                "Connecticut Bank of Commerce", 
                "New Century Bank", 
                "Net 1st National Bank", 
                "NextBank, NA", 
                "Oakwood Deposit Bank Co.", 
                "Bank of Sierra Blanca", 
                "Hamilton Bank, NA", 
                "Sinclair National Bank", 
                "Superior Bank, FSB", 
                "Malta National Bank", 
                "First Alliance Bank & Trust Co.", 
                "National State Bank of Metropolis", 
                "Bank of Honolulu"
            ], 
            "x": [
                "12/15/2017", 
                "10/13/2017", 
                "5/26/2017", 
                "5/5/2017", 
                "4/28/2017", 
                "3/3/2017", 
                "1/27/2017", 
                "1/13/2017", 
                "9/23/2016", 
                "8/19/2016", 
                "5/6/2016", 
                "4/29/2016", 
                "3/11/2016", 
                "10/2/2015", 
                "10/2/2015", 
                "7/10/2015", 
                "5/8/2015", 
                "2/27/2015", 
                "2/13/2015", 
                "1/23/2015", 
                "1/16/2015", 
                "12/19/2014", 
                "11/7/2014", 
                "10/24/2014", 
                "10/17/2014", 
                "7/25/2014", 
                "7/18/2014", 
                "6/27/2014", 
                "6/20/2014", 
                "6/20/2014", 
                "5/30/2014", 
                "5/23/2014", 
                "5/16/2014", 
                "4/25/2014", 
                "2/28/2014", 
                "2/28/2014", 
                "1/31/2014", 
                "1/24/2014", 
                "1/17/2014", 
                "12/13/2013", 
                "10/30/2013", 
                "9/13/2013", 
                "9/13/2013", 
                "8/23/2013", 
                "8/23/2013", 
                "8/9/2013", 
                "8/2/2013", 
                "6/7/2013", 
                "6/6/2013", 
                "5/31/2013", 
                "5/14/2013", 
                "5/10/2013", 
                "5/10/2013", 
                "4/26/2013", 
                "4/26/2013", 
                "4/19/2013", 
                "4/19/2013", 
                "4/19/2013", 
                "4/5/2013", 
                "3/8/2013", 
                "2/15/2013", 
                "1/18/2013", 
                "1/11/2013", 
                "12/14/2012", 
                "11/16/2012", 
                "11/2/2012", 
                "11/2/2012", 
                "10/26/2012", 
                "10/19/2012", 
                "10/19/2012", 
                "10/19/2012", 
                "9/28/2012", 
                "9/14/2012", 
                "9/7/2012", 
                "8/3/2012", 
                "7/27/2012", 
                "7/20/2012", 
                "7/20/2012", 
                "7/20/2012", 
                "7/20/2012", 
                "7/20/2012", 
                "7/13/2012", 
                "7/6/2012", 
                "6/15/2012", 
                "6/15/2012", 
                "6/15/2012", 
                "6/8/2012", 
                "6/8/2012", 
                "6/8/2012", 
                "6/8/2012", 
                "5/18/2012", 
                "5/4/2012", 
                "4/27/2012", 
                "4/27/2012", 
                "4/27/2012", 
                "4/27/2012", 
                "4/27/2012", 
                "4/20/2012", 
                "3/30/2012", 
                "3/23/2012", 
                "3/23/2012", 
                "3/9/2012", 
                "3/2/2012", 
                "2/24/2012", 
                "2/24/2012", 
                "2/10/2012", 
                "2/10/2012", 
                "1/27/2012", 
                "1/27/2012", 
                "1/27/2012", 
                "1/27/2012", 
                "1/20/2012", 
                "1/20/2012", 
                "1/20/2012", 
                "12/16/2011", 
                "12/16/2011", 
                "11/18/2011", 
                "11/18/2011", 
                "11/10/2011", 
                "11/4/2011", 
                "11/4/2011", 
                "10/28/2011", 
                "10/21/2011", 
                "10/21/2011", 
                "10/21/2011", 
                "10/21/2011", 
                "10/14/2011", 
                "10/14/2011", 
                "10/14/2011", 
                "10/14/2011", 
                "10/7/2011", 
                "10/7/2011", 
                "9/30/2011", 
                "9/23/2011", 
                "9/23/2011", 
                "9/9/2011", 
                "9/2/2011", 
                "9/2/2011", 
                "8/19/2011", 
                "8/19/2011", 
                "8/19/2011", 
                "8/18/2011", 
                "8/12/2011", 
                "8/5/2011", 
                "8/5/2011", 
                "7/29/2011", 
                "7/29/2011", 
                "7/29/2011", 
                "7/22/2011", 
                "7/22/2011", 
                "7/22/2011", 
                "7/15/2011", 
                "7/15/2011", 
                "7/15/2011", 
                "7/15/2011", 
                "7/8/2011", 
                "7/8/2011", 
                "7/8/2011", 
                "6/24/2011", 
                "6/17/2011", 
                "6/17/2011", 
                "6/3/2011", 
                "5/27/2011", 
                "5/20/2011", 
                "5/20/2011", 
                "5/20/2011", 
                "5/6/2011", 
                "4/29/2011", 
                "4/29/2011", 
                "4/29/2011", 
                "4/29/2011", 
                "4/29/2011", 
                "4/15/2011", 
                "4/15/2011", 
                "4/15/2011", 
                "4/15/2011", 
                "4/15/2011", 
                "4/15/2011", 
                "4/8/2011", 
                "4/8/2011", 
                "3/25/2011", 
                "3/11/2011", 
                "3/11/2011", 
                "2/25/2011", 
                "2/18/2011", 
                "2/18/2011", 
                "2/18/2011", 
                "2/18/2011", 
                "2/11/2011", 
                "2/11/2011", 
                "2/11/2011", 
                "2/11/2011", 
                "2/4/2011", 
                "2/4/2011", 
                "2/4/2011", 
                "1/28/2011", 
                "1/28/2011", 
                "1/28/2011", 
                "1/28/2011", 
                "1/21/2011", 
                "1/21/2011", 
                "1/21/2011", 
                "1/21/2011", 
                "1/14/2011", 
                "1/7/2011", 
                "1/7/2011", 
                "12/17/2010", 
                "12/17/2010", 
                "12/17/2010", 
                "12/17/2010", 
                "12/17/2010", 
                "12/17/2010", 
                "12/10/2010", 
                "12/10/2010", 
                "11/19/2010", 
                "11/19/2010", 
                "11/19/2010", 
                "11/12/2010", 
                "11/12/2010", 
                "11/12/2010", 
                "11/5/2010", 
                "11/5/2010", 
                "11/5/2010", 
                "11/5/2010", 
                "10/22/2010", 
                "10/22/2010", 
                "10/22/2010", 
                "10/22/2010", 
                "10/22/2010", 
                "10/22/2010", 
                "10/22/2010", 
                "10/15/2010", 
                "10/15/2010", 
                "10/15/2010", 
                "10/1/2010", 
                "10/1/2010", 
                "9/24/2010", 
                "9/24/2010", 
                "9/17/2010", 
                "9/17/2010", 
                "9/17/2010", 
                "9/17/2010", 
                "9/17/2010", 
                "9/17/2010", 
                "9/10/2010", 
                "8/20/2010", 
                "8/20/2010", 
                "8/20/2010", 
                "8/20/2010", 
                "8/20/2010", 
                "8/20/2010", 
                "8/20/2010", 
                "8/20/2010", 
                "8/13/2010", 
                "8/6/2010", 
                "7/30/2010", 
                "7/30/2010", 
                "7/30/2010", 
                "7/30/2010", 
                "7/30/2010", 
                "7/23/2010", 
                "7/23/2010", 
                "7/23/2010", 
                "7/23/2010", 
                "7/23/2010", 
                "7/23/2010", 
                "7/23/2010", 
                "7/16/2010", 
                "7/16/2010", 
                "7/16/2010", 
                "7/16/2010", 
                "7/16/2010", 
                "7/16/2010", 
                "7/9/2010", 
                "7/9/2010", 
                "7/9/2010", 
                "7/9/2010", 
                "6/25/2010", 
                "6/25/2010", 
                "6/25/2010", 
                "6/18/2010", 
                "6/11/2010", 
                "6/4/2010", 
                "6/4/2010", 
                "6/4/2010", 
                "5/28/2010", 
                "5/28/2010", 
                "5/28/2010", 
                "5/28/2010", 
                "5/28/2010", 
                "5/21/2010", 
                "5/14/2010", 
                "5/14/2010", 
                "5/14/2010", 
                "5/14/2010", 
                "5/7/2010", 
                "5/7/2010", 
                "5/7/2010", 
                "5/7/2010", 
                "4/30/2010", 
                "4/30/2010", 
                "4/30/2010", 
                "4/30/2010", 
                "4/30/2010", 
                "4/30/2010", 
                "4/30/2010", 
                "4/23/2010", 
                "4/23/2010", 
                "4/23/2010", 
                "4/23/2010", 
                "4/23/2010", 
                "4/23/2010", 
                "4/23/2010", 
                "4/16/2010", 
                "4/16/2010", 
                "4/16/2010", 
                "4/16/2010", 
                "4/16/2010", 
                "4/16/2010", 
                "4/16/2010", 
                "4/16/2010", 
                "4/9/2010", 
                "3/26/2010", 
                "3/26/2010", 
                "3/26/2010", 
                "3/26/2010", 
                "3/19/2010", 
                "3/19/2010", 
                "3/19/2010", 
                "3/19/2010", 
                "3/19/2010", 
                "3/19/2010", 
                "3/19/2010", 
                "3/12/2010", 
                "3/12/2010", 
                "3/12/2010", 
                "3/11/2010", 
                "3/5/2010", 
                "3/5/2010", 
                "3/5/2010", 
                "3/5/2010", 
                "2/26/2010", 
                "2/26/2010", 
                "2/19/2010", 
                "2/19/2010", 
                "2/19/2010", 
                "2/19/2010", 
                "2/5/2010", 
                "1/29/2010", 
                "1/29/2010", 
                "1/29/2010", 
                "1/29/2010", 
                "1/29/2010", 
                "1/29/2010", 
                "1/22/2010", 
                "1/22/2010", 
                "1/22/2010", 
                "1/22/2010", 
                "1/22/2010", 
                "1/15/2010", 
                "1/15/2010", 
                "1/15/2010", 
                "1/8/2010", 
                "12/18/2009", 
                "12/18/2009", 
                "12/18/2009", 
                "12/18/2009", 
                "12/18/2009", 
                "12/18/2009", 
                "12/18/2009", 
                "12/11/2009", 
                "12/11/2009", 
                "12/11/2009", 
                "12/4/2009", 
                "12/4/2009", 
                "12/4/2009", 
                "12/4/2009", 
                "12/4/2009", 
                "12/4/2009", 
                "11/20/2009", 
                "11/13/2009", 
                "11/13/2009", 
                "11/13/2009", 
                "11/6/2009", 
                "11/6/2009", 
                "11/6/2009", 
                "11/6/2009", 
                "11/6/2009", 
                "10/30/2009", 
                "10/30/2009", 
                "10/30/2009", 
                "10/30/2009", 
                "10/30/2009", 
                "10/30/2009", 
                "10/30/2009", 
                "10/30/2009", 
                "10/30/2009", 
                "10/23/2009", 
                "10/23/2009", 
                "10/23/2009", 
                "10/23/2009", 
                "10/23/2009", 
                "10/23/2009", 
                "10/23/2009", 
                "10/16/2009", 
                "10/2/2009", 
                "10/2/2009", 
                "10/2/2009", 
                "9/25/2009", 
                "9/18/2009", 
                "9/18/2009", 
                "9/11/2009", 
                "9/11/2009", 
                "9/11/2009", 
                "9/4/2009", 
                "9/4/2009", 
                "9/4/2009", 
                "9/4/2009", 
                "9/4/2009", 
                "8/28/2009", 
                "8/28/2009", 
                "8/28/2009", 
                "8/21/2009", 
                "8/21/2009", 
                "8/21/2009", 
                "8/21/2009", 
                "8/14/2009", 
                "8/14/2009", 
                "8/14/2009", 
                "8/14/2009", 
                "8/14/2009", 
                "8/7/2009", 
                "8/7/2009", 
                "8/7/2009", 
                "7/31/2009", 
                "7/31/2009", 
                "7/31/2009", 
                "7/31/2009", 
                "7/31/2009", 
                "7/24/2009", 
                "7/24/2009", 
                "7/24/2009", 
                "7/24/2009", 
                "7/24/2009", 
                "7/24/2009", 
                "7/24/2009", 
                "7/17/2009", 
                "7/17/2009", 
                "7/17/2009", 
                "7/17/2009", 
                "7/10/2009", 
                "7/2/2009", 
                "7/2/2009", 
                "7/2/2009", 
                "7/2/2009", 
                "7/2/2009", 
                "7/2/2009", 
                "7/2/2009", 
                "6/26/2009", 
                "6/26/2009", 
                "6/26/2009", 
                "6/26/2009", 
                "6/26/2009", 
                "6/19/2009", 
                "6/19/2009", 
                "6/19/2009", 
                "6/5/2009", 
                "5/22/2009", 
                "5/22/2009", 
                "5/21/2009", 
                "5/8/2009", 
                "5/1/2009", 
                "5/1/2009", 
                "5/1/2009", 
                "4/24/2009", 
                "4/24/2009", 
                "4/24/2009", 
                "4/24/2009", 
                "4/17/2009", 
                "4/17/2009", 
                "4/10/2009", 
                "4/10/2009", 
                "3/27/2009", 
                "3/20/2009", 
                "3/20/2009", 
                "3/20/2009", 
                "3/6/2009", 
                "2/27/2009", 
                "2/27/2009", 
                "2/20/2009", 
                "2/13/2009", 
                "2/13/2009", 
                "2/13/2009", 
                "2/13/2009", 
                "2/6/2009", 
                "2/6/2009", 
                "2/6/2009", 
                "1/30/2009", 
                "1/30/2009", 
                "1/30/2009", 
                "1/23/2009", 
                "1/16/2009", 
                "1/16/2009", 
                "12/12/2008", 
                "12/12/2008", 
                "12/5/2008", 
                "11/21/2008", 
                "11/21/2008", 
                "11/21/2008", 
                "11/7/2008", 
                "11/7/2008", 
                "10/31/2008", 
                "10/24/2008", 
                "10/10/2008", 
                "10/10/2008", 
                "9/25/2008", 
                "9/19/2008", 
                "9/5/2008", 
                "8/29/2008", 
                "8/22/2008", 
                "8/1/2008", 
                "7/25/2008", 
                "7/25/2008", 
                "7/11/2008", 
                "5/30/2008", 
                "5/9/2008", 
                "3/7/2008", 
                "1/25/2008", 
                "10/4/2007", 
                "9/28/2007", 
                "2/2/2007", 
                "6/25/2004", 
                "3/19/2004", 
                "3/12/2004", 
                "2/14/2004", 
                "11/14/2003", 
                "5/9/2003", 
                "2/7/2003", 
                "12/17/2002", 
                "11/8/2002", 
                "9/30/2002", 
                "6/27/2002", 
                "6/26/2002", 
                "3/28/2002", 
                "3/1/2002", 
                "2/7/2002", 
                "2/1/2002", 
                "1/18/2002", 
                "1/11/2002", 
                "9/7/2001", 
                "7/27/2001", 
                "5/3/2001", 
                "2/2/2001", 
                "12/14/2000", 
                "10/13/2000"
            ], 
            "type": "scatter"
        }
    ]
}